server:
  port: 8095
  servlet:
    context-path: /shop
    multipart:
      max-file-size: 10MB  #单个文件
      max-request-size: 100MB #总文件大小
    jsp:
      init-parameters: true

spring:
     datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/bread_system?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
        username: root
        password: 12345678
        hikari:
          #客户端等待连接池连接的最大毫秒数
          connection-timeout: 20000
          #HikariCP在连接池中维护的最小空闲连接数
          minimum-idle: 5
          #配置最大池的大小
          maximum-pool-size: 12
          #允许连接在连接池中空闲的最长时间（以毫秒为单位）
          idle-timeout: 300000
          #池中连接关闭后的最长生命周期（以毫秒为单位）
          max-lifetime: 1200000
          #从池返回的连接的默认自动提交行为
          auto-commit: true
     jpa:
       show-sql: true
     mvc:
       view:
         prefix: /WEB-INF/views/
         suffix: .jsp


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cxxy.bysj.entity
   #devtools插件
devtools:
    restart:
      enabled: true #是否支持热部署
#mybaatis分页插件pagehelper设置
pagehelper:
  pagehelperDialect: mysql
  reasonable: true
  support-methods-arguments: true

  # 打印sql
logging:
    level:
       com.cxxy.bysj.dao: DEBUG
