server:
  port: 8099

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopsystem2?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      #客户端等待连接池连接的最大毫秒数
      connection-timeout: 20000
      #HikariCP在连接池中维护的最小空闲连接数
      minimum-idle: 5
      #配置最大池的大小
      maximum-pool-size: 12
      #允许连接在连接池中空闲的最长时间（以毫秒为单位）
      idle-timeout: 300000
      #池中连接关闭后的最长生命周期（以毫秒为单位）
      max-lifetime: 1200000
      #从池返回的连接的默认自动提交行为
      auto-commit: true
  mvc:
    view:
      suffix: .jsp
      prefix: /

#mybatis驼峰命令启用设置
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    map-underscore-to-camel-case: true